### ISSUE TITLE
ImportError: No module named 'zproject.dev_settings'

### ISSUE THREAD

**Issue by zingmars** [zulip/docker-zulip#129]
After rebooting the machine I had set up a test instance of docker-zulip on it now refuses to run. The only thing I did on this machine since it last worked was change some unrelated iptables settings and rebooted it. 

```
zulip_1      | === Begin Initial Configuration Phase ===
zulip_1      | Preparing and linking the uploads folder ...
zulip_1      | Prepared and linked the uploads directory.
zulip_1      | Executing nginx configuration ...
zulip_1      | Nginx configuration succeeded.
zulip_1      | Exectuing certificates configuration...
zulip_1      | Certificates configuration succeeded.
zulip_1      | Setting database configuration ...
zulip_1      | Setting key "DATABASES", type "array" in file "/home/zulip/deployments/current/zproject/settings.py".
zulip_1      | Setting key "REMOTE_POSTGRES_HOST", type "string" in file "/etc/zulip/settings.py".
zulip_1      | Setting key "REMOTE_POSTGRES_SSLMODE", type "string" in file "/etc/zulip/settings.py".
zulip_1      | Database configuration succeeded.
zulip_1      | Setting Zulip secrets ...
zulip_1      | Secrets already generated/existing.
zulip_1      | Secret found for "rabbitmq_password".
zulip_1      | Secret found for "email_password".
zulip_1      | Secret found for "secret_key".
zulip_1      | Linking secrets from data dir to etc zulip  ...
zulip_1      | Linked existing secrets from data dir to etc zulip.
zulip_1      | Zulip secrets configuration succeeded.
zulip_1      | Activating authentication backends ...
zulip_1      | Setting key "AUTHENTICATION_BACKENDS", type "array" in file "/etc/zulip/settings.py".
zulip_1      | Adding authentication backend "EmailAuthBackend".
zulip_1      | Authentication backend activation succeeded.
zulip_1      | Executing Zulip configuration ...
zulip_1      | Setting key "EXTERNAL_HOST", type "string" in file "/etc/zulip/settings.py".
zulip_1      | Setting key "EMAIL_HOST", type "string" in file "/etc/zulip/settings.py".
zulip_1      | Setting key "ALLOWED_HOSTS", type "array" in file "/etc/zulip/settings.py".
zulip_1      | Setting key "NOREPLY_EMAIL_ADDRESS", type "string" in file "/etc/zulip/settings.py".
zulip_1      | Setting key "ZULIP_ADMINISTRATOR", type "string" in file "/etc/zulip/settings.py".
zulip_1      | Setting key "REDIS_HOST", type "string" in file "/etc/zulip/settings.py".
zulip_1      | Setting key "RABBITMQ_HOST", type "string" in file "/etc/zulip/settings.py".
zulip_1      | Setting key "PUSH_NOTIFICATION_BOUNCER_URL", type "string" in file "/home/zulip/deployments/current/zproject/settings.py".
zulip_1      | Setting key "EMAIL_HOST_USER", type "string" in file "/etc/zulip/settings.py".
zulip_1      | Setting key "DEFAULT_FROM_EMAIL", type "string" in file "/etc/zulip/settings.py".
zulip_1      | Setting key "MEMCACHED_LOCATION", type "string" in file "/etc/zulip/settings.py".
zulip_1      | Setting key "EMAIL_USE_SSL", type "bool" in file "/etc/zulip/settings.py".
zulip_1      | Setting key "ADMIN_DOMAIN", type "string" in file "/etc/zulip/settings.py".
zulip_1      | Setting key "EMAIL_USE_TLS", type "bool" in file "/etc/zulip/settings.py".
zulip_1      | Setting key "EMAIL_PORT", type "integer" in file "/etc/zulip/settings.py".
zulip_1      | Traceback (most recent call last):
zulip_1      |   File "/home/zulip/deployments/current/manage.py", line 19, in <module>
zulip_1      |     log_management_command(" ".join(sys.argv), settings.MANAGEMENT_LOG_PATH)
zulip_1      |   File "/home/zulip/deployments/2018-05-08-09-59-46/zulip-py3-venv/lib/python3.5/site-packages/django/conf/__init__.py", line 56, in __getattr__
zulip_1      |     self._setup(name)
zulip_1      |   File "/home/zulip/deployments/2018-05-08-09-59-46/zulip-py3-venv/lib/python3.5/site-packages/django/conf/__init__.py", line 41, in _setup
zulip_1      |     self._wrapped = Settings(settings_module)
zulip_1      |   File "/home/zulip/deployments/2018-05-08-09-59-46/zulip-py3-venv/lib/python3.5/site-packages/django/conf/__init__.py", line 110, in __init__
zulip_1      |     mod = importlib.import_module(self.SETTINGS_MODULE)
zulip_1      |   File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
zulip_1      |     return _bootstrap._gcd_import(name[level:], package, level)
zulip_1      |   File "<frozen importlib._bootstrap>", line 986, in _gcd_import
zulip_1      |   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
zulip_1      |   File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
zulip_1      |   File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
zulip_1      |   File "<frozen importlib._bootstrap_external>", line 665, in exec_module
zulip_1      |   File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
zulip_1      |   File "/home/zulip/deployments/2018-05-08-09-59-46/zproject/settings.py", line 104, in <module>
zulip_1      |     from .dev_settings import *
zulip_1      | ImportError: No module named 'zproject.dev_settings'
```

Also, reading `data/settings/etc-zulip/settings.py`, it seems that it re-adds all the settings entry every time it tries to run the instance even if the keys are present. Which is fun, because I now have at least 20 duplicate entries there. 

Here's my docker-compose.yml -

```
version: '2'
services:
  database:
    restart: always
    # https://github.com/zulip/docker-zulip/issues/123
    #    image: "zulip/zulip-postgresql" 
    image: "quay.io/galexrt/postgres-zulip-tsearchextras:latest"
    environment:
      POSTGRES_DB: <removed>
      POSTGRES_USER: <removed>
      POSTGRES_PASSWORD: <removed>
    volumes:
      - "/var/www/zulip/db:/var/lib/postgresql/data:rw"
  memcached:
    image: "quay.io/sameersbn/memcached:latest"
    restart: always
  rabbitmq:
    image: "rabbitmq:3.5.5"
    hostname: zulip-rabbit
    restart: always
    environment:
        RABBITMQ_DEFAULT_USER: "<removed>"
        RABBITMQ_DEFAULT_PASS: "<removed>"
  redis:
    restart: always
    image: "quay.io/sameersbn/redis:latest"
    volumes:
      - "/var/www/zulip/redis:/var/lib/redis:rw"
  zulip:
    restart: always
    image: "quay.io/galexrt/zulip:1.8.1-0"
    ports:
      - "127.0.0.1:8002:443"
    environment:
      DB_HOST: "database"
      DB_USER: "<removed>"
      DB_PASS: "<removed>"
      SSL_CERTIFICATE_GENERATION: "self-signed"
      SETTING_MEMCACHED_LOCATION: "memcached:11211"
      SETTING_RABBITMQ_HOST: "rabbitmq"
      SETTING_REDIS_HOST: "redis"
      SECRETS_rabbitmq_password: "<removed>"
      SECRETS_secret_key: "<removed>"
      SETTING_EXTERNAL_HOST: "<removed>"
      SETTING_PUSH_NOTIFICATION_BOUNCER_URL: "https://push.zulipchat.com"
      LINK_SETTINGS_TO_DATA: "true"
      SETTING_ZULIP_ADMINISTRATOR: "<removed>"
      SETTING_ADMIN_DOMAIN: "<removed>"
      SETTING_NOREPLY_EMAIL_ADDRESS: "<removed>"
      SETTING_DEFAULT_FROM_EMAIL: "<removed>"
      SETTING_EMAIL_HOST: "<removed>"
      SETTING_EMAIL_HOST_USER: "<removed>"
      SECRETS_email_password: "<removed>"
      SETTING_EMAIL_PORT: "587"
      SETTING_EMAIL_USE_SSL: "False"
      SETTING_EMAIL_USE_TLS: "True"
      SETTING_ALLOWED_HOSTS: "[ '*' ]"
      ZULIP_AUTH_BACKENDS: "EmailAuthBackend"
      ZULIP_USER_CREATION_ENABLED: "False"
    volumes:
      - "/var/www/zulip/data:/data:rw"
```
