### ISSUE TITLE
Zulip container doesn't find Database

### ISSUE THREAD

**Issue by shinsei90** [zulip/docker-zulip#184]
Hi!

I am trying to run docker-zulip on our `localhost.localdomain` as a test, but after seemingly everything sets up, for some reason the zulip container doesn't find the postgresql database included.

Here is what i get as an output after runing `docker-compose up`:
```
Starting docker-zulip_rabbitmq_1  ... done
Starting docker-zulip_redis_1     ... done
Starting docker-zulip_memcached_1 ... done
Starting docker-zulip_database_1  ... done
Starting docker-zulip_zulip_1     ... done
Attaching to docker-zulip_redis_1, docker-zulip_database_1, docker-zulip_rabbitmq_1, docker-zulip_memcached_1, docker-zulip_zulip_1
redis_1      | Starting redis-server...
redis_1      | 1:C 22 Feb 11:49:21.419 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1      | 1:C 22 Feb 11:49:21.419 # Redis version=4.0.9, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1      | 1:C 22 Feb 11:49:21.419 # Configuration loaded
redis_1      |                 _._
redis_1      |            _.-``__ ''-._
redis_1      |       _.-``    `.  `_.  ''-._           Redis 4.0.9 (00000000/0) 64 bit
redis_1      |   .-`` .-```.  ```\/    _.,_ ''-._
redis_1      |  (    '      ,       .-`  | `,    )     Running in standalone mode
redis_1      |  |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
redis_1      |  |    `-._   `._    /     _.-'    |     PID: 1
redis_1      |   `-._    `-._  `-./  _.-'    _.-'
redis_1      |  |`-._`-._    `-.__.-'    _.-'_.-'|
redis_1      |  |    `-._`-._        _.-'_.-'    |           http://redis.io
redis_1      |   `-._    `-._`-.__.-'_.-'    _.-'
redis_1      |  |`-._`-._    `-.__.-'    _.-'_.-'|
redis_1      |  |    `-._`-._        _.-'_.-'    |
redis_1      |   `-._    `-._`-.__.-'_.-'    _.-'
redis_1      |       `-._    `-.__.-'    _.-'
redis_1      |           `-._        _.-'
redis_1      |               `-.__.-'
redis_1      |
redis_1      | 1:M 22 Feb 11:49:21.422 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis_1      | 1:M 22 Feb 11:49:21.422 # Server initialized
redis_1      | 1:M 22 Feb 11:49:21.422 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis_1      | 1:M 22 Feb 11:49:21.423 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
redis_1      | 1:M 22 Feb 11:49:21.439 * DB loaded from disk: 0.016 seconds
redis_1      | 1:M 22 Feb 11:49:21.439 * Ready to accept connections
redis_1      | 1:M 22 Feb 11:49:21.439 * The server is now ready to accept connections at /var/run/redis/redis-server.sock
database_1   | 2019-02-22 11:49:22.637 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
database_1   | 2019-02-22 11:49:22.638 UTC [1] LOG:  listening on IPv6 address "::", port 5432
database_1   | 2019-02-22 11:49:22.713 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
database_1   | 2019-02-22 11:49:22.919 UTC [23] LOG:  database system was shut down at 2019-02-22 10:00:45 UTC
database_1   | 2019-02-22 11:49:23.108 UTC [1] LOG:  database system is ready to accept connections
zulip_1      | === Begin Initial Configuration Phase ===
zulip_1      | Preparing and linking the uploads folder ...
zulip_1      | Prepared and linked the uploads directory.
zulip_1      | Executing nginx configuration ...
zulip_1      | Nginx configuration succeeded.
zulip_1      | Certificates configuration succeeded.
zulip_1      | Setting database configuration ...
zulip_1      | Setting key "REMOTE_POSTGRES_HOST", type "string" in file "/etc/zulip/settings.py".
zulip_1      | Setting key "REMOTE_POSTGRES_SSLMODE", type "string" in file "/etc/zulip/settings.py".
zulip_1      | Database configuration succeeded.
zulip_1      | Setting Zulip secrets ...
zulip_1      | Secrets already generated/existing.
zulip_1      | Zulip secrets configuration succeeded.
zulip_1      | Activating authentication backends ...
zulip_1      | Setting key "AUTHENTICATION_BACKENDS", type "array" in file "/etc/zulip/settings.py".
zulip_1      | Adding authentication backend "EmailAuthBackend".
zulip_1      | Authentication backend activation succeeded.
zulip_1      | Executing Zulip configuration ...
zulip_1      | Setting key "EXTERNAL_HOST", type "string" in file "/etc/zulip/settings.py".
zulip_1      | Setting key "EMAIL_HOST", type "string" in file "/etc/zulip/settings.py".
zulip_1      | Setting key "ZULIP_ADMINISTRATOR", type "string" in file "/etc/zulip/settings.py".
zulip_1      | Setting key "REDIS_HOST", type "string" in file "/etc/zulip/settings.py".
zulip_1      | Setting key "RABBITMQ_HOST", type "string" in file "/etc/zulip/settings.py".
zulip_1      | Setting key "EMAIL_HOST_USER", type "string" in file "/etc/zulip/settings.py".
zulip_1      | Setting key "MEMCACHED_LOCATION", type "string" in file "/etc/zulip/settings.py".
zulip_1      | Setting key "EMAIL_USE_SSL", type "bool" in file "/etc/zulip/settings.py".
zulip_1      | Setting key "EMAIL_USE_TLS", type "bool" in file "/etc/zulip/settings.py".
zulip_1      | Setting key "EMAIL_PORT", type "integer" in file "/etc/zulip/settings.py".
zulip_1      | Zulip configuration succeeded.
zulip_1      | Auto backup enabled.
zulip_1      | === End Initial Configuration Phase ===
zulip_1      | === Begin Bootstrap Phase ===
zulip_1      | Waiting for database server to allow connections ...
rabbitmq_1   | 2019-02-22 11:49:34.298 [info] <0.33.0> Application lager started on node 'rabbit@zulip-rabbit'
rabbitmq_1   | 2019-02-22 11:49:39.710 [info] <0.33.0> Application mnesia started on node 'rabbit@zulip-rabbit'
rabbitmq_1   | 2019-02-22 11:49:39.711 [info] <0.33.0> Application crypto started on node 'rabbit@zulip-rabbit'
rabbitmq_1   | 2019-02-22 11:49:39.711 [info] <0.33.0> Application recon started on node 'rabbit@zulip-rabbit'
rabbitmq_1   | 2019-02-22 11:49:39.711 [info] <0.33.0> Application jsx started on node 'rabbit@zulip-rabbit'
rabbitmq_1   | 2019-02-22 11:49:39.711 [info] <0.33.0> Application os_mon started on node 'rabbit@zulip-rabbit'
rabbitmq_1   | 2019-02-22 11:49:39.712 [info] <0.33.0> Application xmerl started on node 'rabbit@zulip-rabbit'
rabbitmq_1   | 2019-02-22 11:49:39.713 [info] <0.33.0> Application inets started on node 'rabbit@zulip-rabbit'
rabbitmq_1   | 2019-02-22 11:49:39.713 [info] <0.33.0> Application asn1 started on node 'rabbit@zulip-rabbit'
rabbitmq_1   | 2019-02-22 11:49:39.713 [info] <0.33.0> Application public_key started on node 'rabbit@zulip-rabbit'
rabbitmq_1   | 2019-02-22 11:49:39.714 [info] <0.33.0> Application ssl started on node 'rabbit@zulip-rabbit'
rabbitmq_1   | 2019-02-22 11:49:39.714 [info] <0.33.0> Application ranch started on node 'rabbit@zulip-rabbit'
rabbitmq_1   | 2019-02-22 11:49:39.714 [info] <0.33.0> Application ranch_proxy_protocol started on node 'rabbit@zulip-rabbit'
rabbitmq_1   | 2019-02-22 11:49:39.714 [info] <0.33.0> Application rabbit_common started on node 'rabbit@zulip-rabbit'
rabbitmq_1   | 2019-02-22 11:49:39.716 [info] <0.220.0>
rabbitmq_1   |  Starting RabbitMQ 3.7.7 on Erlang 20.3.8.5
rabbitmq_1   |  Copyright (C) 2007-2018 Pivotal Software, Inc.
rabbitmq_1   |  Licensed under the MPL.  See http://www.rabbitmq.com/
rabbitmq_1   |
rabbitmq_1   |   ##  ##
rabbitmq_1   |   ##  ##      RabbitMQ 3.7.7. Copyright (C) 2007-2018 Pivotal Software, Inc.
rabbitmq_1   |   ##########  Licensed under the MPL.  See http://www.rabbitmq.com/
rabbitmq_1   |   ######  ##
rabbitmq_1   |   ##########  Logs: <stdout>
rabbitmq_1   |
rabbitmq_1   |               Starting broker...
rabbitmq_1   | 2019-02-22 11:49:39.718 [info] <0.220.0>
rabbitmq_1   |  node           : rabbit@zulip-rabbit
rabbitmq_1   |  home dir       : /var/lib/rabbitmq
rabbitmq_1   |  config file(s) : /etc/rabbitmq/rabbitmq.conf
rabbitmq_1   |  cookie hash    : FmuAMCiqpTpm/tNcAFVqgg==
rabbitmq_1   |  log(s)         : <stdout>
rabbitmq_1   |  database dir   : /var/lib/rabbitmq/mnesia/rabbit@zulip-rabbit
rabbitmq_1   | 2019-02-22 11:49:39.749 [info] <0.257.0> Memory high watermark set to 51562 MiB (54067283558 bytes) of 128906 MiB (135168208896 bytes) total
rabbitmq_1   | 2019-02-22 11:49:39.759 [info] <0.259.0> Enabling free disk space monitoring
rabbitmq_1   | 2019-02-22 11:49:39.759 [info] <0.259.0> Disk free limit set to 50MB
rabbitmq_1   | 2019-02-22 11:49:39.768 [info] <0.261.0> Limiting to approx 1048476 file handles (943626 sockets)
rabbitmq_1   | 2019-02-22 11:49:39.768 [info] <0.262.0> FHC read buffering:  OFF
rabbitmq_1   | 2019-02-22 11:49:39.768 [info] <0.262.0> FHC write buffering: ON
rabbitmq_1   | 2019-02-22 11:49:39.777 [info] <0.220.0> Waiting for Mnesia tables for 30000 ms, 9 retries left
rabbitmq_1   | 2019-02-22 11:49:39.887 [info] <0.220.0> Waiting for Mnesia tables for 30000 ms, 9 retries left
rabbitmq_1   | 2019-02-22 11:49:39.888 [info] <0.220.0> Peer discovery backend rabbit_peer_discovery_classic_config does not support registration, skipping registration.
rabbitmq_1   | 2019-02-22 11:49:39.889 [info] <0.220.0> Priority queues enabled, real BQ is rabbit_variable_queue
rabbitmq_1   | 2019-02-22 11:49:39.929 [info] <0.344.0> Starting rabbit_node_monitor
rabbitmq_1   | 2019-02-22 11:49:39.962 [info] <0.372.0> Making sure data directory '/var/lib/rabbitmq/mnesia/rabbit@zulip-rabbit/msg_stores/vhosts/628WB79CIFDYO9LJI6DKMI09L' for vhost '/' exists
rabbitmq_1   | 2019-02-22 11:49:40.012 [info] <0.372.0> Starting message stores for vhost '/'
rabbitmq_1   | 2019-02-22 11:49:40.013 [info] <0.376.0> Message store "628WB79CIFDYO9LJI6DKMI09L/msg_store_transient": using rabbit_msg_store_ets_index to provide index
rabbitmq_1   | 2019-02-22 11:49:40.019 [info] <0.372.0> Started message store of type transient for vhost '/'
rabbitmq_1   | 2019-02-22 11:49:40.020 [info] <0.379.0> Message store "628WB79CIFDYO9LJI6DKMI09L/msg_store_persistent": using rabbit_msg_store_ets_index to provide index
rabbitmq_1   | 2019-02-22 11:49:40.027 [info] <0.372.0> Started message store of type persistent for vhost '/'
rabbitmq_1   | 2019-02-22 11:49:40.034 [info] <0.414.0> started TCP Listener on [::]:5672
rabbitmq_1   | 2019-02-22 11:49:40.035 [info] <0.220.0> Setting up a table for connection tracking on this node: 'tracked_connection_on_node_rabbit@zulip-rabbit'
rabbitmq_1   | 2019-02-22 11:49:40.035 [info] <0.220.0> Setting up a table for per-vhost connection counting on this node: 'tracked_connection_per_vhost_on_node_rabbit@zulip-rabbit'
rabbitmq_1   | 2019-02-22 11:49:40.036 [info] <0.33.0> Application rabbit started on node 'rabbit@zulip-rabbit'
rabbitmq_1   |  completed with 0 plugins.
rabbitmq_1   | 2019-02-22 11:49:40.369 [info] <0.5.0> Server startup complete; 0 plugins started.
zulip_1      | ...........................................................docker-zulip_zulip_1 exited with code 1
```

Here is for further information my `docker-compose.yml`:
```yaml
version: '2'
services:
  database:
    image: 'zulip/zulip-postgresql'
    environment:
      POSTGRES_DB: zulip
      POSTGRES_USER: zulip
      POSTGRES_PASSWORD: ***************
    volumes:
      - '/opt/docker/zulip/postgresql/data:/var/lib/postgresql/data:rw'
  memcached:
    image: 'quay.io/sameersbn/memcached:latest'
    restart: always
  rabbitmq:
    image: 'rabbitmq:3.7.7'
    hostname: zulip-rabbit
    restart: always
    environment:
        RABBITMQ_DEFAULT_USER: 'zulip'
        RABBITMQ_DEFAULT_PASS: '***************'
    volumes:
      - '/opt/docker/zulip/rabbitmq:/var/lib/rabbitmq:rw'
  redis:
    image: 'quay.io/sameersbn/redis:latest'
    volumes:
      - '/opt/docker/zulip/redis:/var/lib/redis:rw'
  zulip:
    image: 'zulip/docker-zulip:1.9.0-0'
    build:
      context: .
      args:
        # Change these if you want to build zulip from a different repo/branch
        ZULIP_GIT_URL: https://github.com/zulip/zulip.git
        ZULIP_GIT_REF: 1.9.0
        # Set this up if you plan to use your own CA certificate bundle for building
        # CUSTOM_CA_CERTIFICATES:
    ports:
      - '8080:80'
      - '443:443'
    environment:
      DB_HOST: '127.0.0.1'
      DB_HOST_PORT: '5432'
      DB_USER: 'zulip'
      SSL_CERTIFICATE_GENERATION: 'self-signed'
      SETTING_MEMCACHED_LOCATION: 'memcached:11211'
      SETTING_RABBITMQ_HOST: 'rabbitmq'
      SETTING_REDIS_HOST: 'redis'
      SECRETS_email_password: '***************'
      SECRETS_rabbitmq_password: '***************'
      SECRETS_postgres_password: '***************'
      SECRETS_secret_key: '****************************'
      SETTING_EXTERNAL_HOST: 'localhost.localdomain'
      SETTING_ZULIP_ADMINISTRATOR: 'my@email.com'
      SETTING_EMAIL_HOST: 'smtp.server.com'  # e.g. smtp.example.com
      SETTING_EMAIL_HOST_USER: 'my@email.com'
      SETTING_EMAIL_PORT: '587'
      # It seems that the email server needs to use ssl or tls and can't be used without it
      SETTING_EMAIL_USE_SSL: 'False'
      SETTING_EMAIL_USE_TLS: 'True'
      ZULIP_AUTH_BACKENDS: 'EmailAuthBackend'
      # Uncomment this when configuring the mobile push notifications service
      # SETTING_PUSH_NOTIFICATION_BOUNCER_URL: 'https://push.zulipchat.com'
    volumes:
      - '/opt/docker/zulip/zulip:/data:rw'
    ulimits:
      nofile:
        soft: 40000
        hard: 50000
```
