### ISSUE TITLE
Memory recommendations for docker on macOS

### ISSUE THREAD

**Issue by jby** [zulip/docker-zulip#188]
Documentations should perhaps be updated stating that if running docker on macOS you should increase the default amount of memory for your containers.

2GB (which is default) is *not* enough for the zulip-container, see discussion and examples of errors in https://chat.zulip.org/#narrow/stream/31-production-help/topic/2.2E0.2E0.20in.20docker

**Comment by timabbott** [comment]
I don't think that's the correct analysis; Zulip makes different decisions about how many processes to run depending on the system's memory, and in particular there's a cutoff around 4GB to use much more memory.  I'd be curious to see details on a system with 2GB of memory running Zulip where one is having problems with the memory allocation.

**Comment by jby** [comment]
I've given up my attempts to get Zulip running and importing HipChat-data.
Trying out 2 competitors instead at the moment.

**Comment by meetmangukiya** [comment]
Can confirm, docker-zulip runs out of memory on a 2GB runtime. However, running zulip with docker-zulip had worked from the zulip 1-click droplet - https://marketplace.digitalocean.com/apps/zulip. I am still trying to get docker-zulip running though.

**Comment by timabbott** [comment]
@meetmangukiya can you provide more detail on the precise configuration you tested?

**Comment by timabbott** [comment]
(Note that the Digital Ocean thing doesn't use Docker)

**Comment by meetmangukiya** [comment]
Yes, that was the point without docker it seems to work well even on 2GB of ram. I tried on a new droplet with 4GB ram and 2 CPU, works well, but consumes almost all the run making it unsuitable for any more services on the server. Not sure what are the official specs required for running a one organization zulip.

This is the compose file I am using, only some config is changed as required and suggested in README.
```yml
version: '2'
services:
  database:
    image: 'zulip/zulip-postgresql:10'
    environment:
      POSTGRES_DB: 'zulip'
      POSTGRES_USER: 'zulip'
      # Note that you need to do a manual `ALTER ROLE` query if you
      # change this on a system after booting the postgres container
      # the first time on a host.  Instructions are available in README.md.
      POSTGRES_PASSWORD: '****'
    volumes:
      - '/opt/docker/zulip/postgresql/data:/var/lib/postgresql/data:rw'
  memcached:
    image: 'memcached:alpine'
    command:
      - 'sh'
      - '-euc'
      - |
        echo 'mech_list: plain' > "$$SASL_CONF_PATH"
        echo "zulip@$$HOSTNAME:$$MEMCACHED_PASSWORD" > "$$MEMCACHED_SASL_PWDB"
        echo "zulip@localhost:$$MEMCACHED_PASSWORD" >> "$$MEMCACHED_SASL_PWDB"
        exec memcached -S
    environment:
      SASL_CONF_PATH: '/home/memcache/memcached.conf'
      MEMCACHED_SASL_PWDB: '/home/memcache/memcached-sasl-db'
      MEMCACHED_PASSWORD: '****'
    restart: always
  rabbitmq:
    image: 'rabbitmq:3.7.7'
    hostname: zulip-rabbit
    restart: always
    environment:
        RABBITMQ_DEFAULT_USER: 'zulip'
        RABBITMQ_DEFAULT_PASS: '****'
    volumes:
      - '/opt/docker/zulip/rabbitmq:/var/lib/rabbitmq:rw'
  redis:
    image: 'redis:alpine'
    command:
      - 'sh'
      - '-euc'
      - |
        echo "requirepass '$$REDIS_PASSWORD'" > /etc/redis.conf
        exec redis-server /etc/redis.conf
    environment:
      REDIS_PASSWORD: '****'
    volumes:
      - '/opt/docker/zulip/redis:/data:rw'
  zulip:
    image: 'zulip/docker-zulip:3.0-0'
    build:
      context: .
      args:
        # Change these if you want to build zulip from a different repo/branch
        ZULIP_GIT_URL: https://github.com/zulip/zulip.git
        ZULIP_GIT_REF: 3.0
        # Set this up if you plan to use your own CA certificate bundle for building
        # CUSTOM_CA_CERTIFICATES:
    ports:
      - '8088:80'
      - '8089:443'
    environment:
      DB_HOST: 'database'
      DB_HOST_PORT: '5432'
      DB_USER: 'zulip'
      SSL_CERTIFICATE_GENERATION: 'self-signed'
      SETTING_MEMCACHED_LOCATION: 'memcached:11211'
      SETTING_RABBITMQ_HOST: 'rabbitmq'
      SETTING_REDIS_HOST: 'redis'
      SECRETS_email_password: '****'
      # These should match RABBITMQ_DEFAULT_PASS, POSTGRES_PASSWORD,
      # MEMCACHED_PASSWORD, and REDIS_PASSWORD above.
      SECRETS_rabbitmq_password: '****'
      SECRETS_postgres_password: '****'
      SECRETS_memcached_password: '****'
      SECRETS_redis_password: '****'
      SECRETS_secret_key: '****'
      SETTING_EXTERNAL_HOST: 'zulip.flamy.dev'
      SETTING_ALLOWED_HOSTS: "['zulip.flamy.dev', '127.0.0.1']"
      SETTING_ZULIP_ADMINISTRATOR: 'zulip@flamy.dev'
      SETTING_USE_X_FORWARDED_HOST: "True"
      SETTING_EMAIL_HOST: 'smtp.sendgrid.net'  # e.g. smtp.example.com
      SETTING_EMAIL_HOST_USER: 'apikey'
      SETTING_EMAIL_PORT: '587'
      SETTING_ADD_TOKENS_TO_NOREPLY_ADDRESS: 'False'
      # It seems that the email server needs to use ssl or tls and can't be used without it
      SETTING_EMAIL_USE_SSL: 'False'
      SETTING_EMAIL_USE_TLS: 'True'
      SETTING_NOREPLY_EMAIL_ADDRESS: 'zulip-noreply@flamy.dev'
      ZULIP_AUTH_BACKENDS: 'EmailAuthBackend'
      # Uncomment this when configuring the mobile push notifications service
      SETTING_PUSH_NOTIFICATION_BOUNCER_URL: 'https://push.zulipchat.com'
    volumes:
      - '/opt/docker/zulip/zulip:/data:rw'
    ulimits:
      nofile:
        soft: 40000
        hard: 50000
```
