### ISSUE TITLE
Tag 2.1.3 is not yet published on docker hub

### ISSUE THREAD

**Issue by stratosgear** [zulip/docker-zulip#247]
https://hub.docker.com/r/zulip/docker-zulip/tags

Is this something that lags after publishing a new release?

I could pull with :latest but I'd rather point to a specific version.

Thanks!

**Comment by maltokyo** [comment]
I had same issue


    `image: 'zulip/docker-zulip:2.1.3-0'` was not found.
But I could build it myself using this in docker-compose.yml:
```
    build:
      context: .
      args:
        # Change these if you want to build zulip from a different repo/branch
        ZULIP_GIT_URL: https://github.com/zulip/zulip.git
        ZULIP_GIT_REF: 2.1.3
        # Set this up if you plan to use your own CA certificate bundle for building
        # CUSTOM_CA_CERTIFICATES:
```
