### ISSUE TITLE
ERROR: Cannot locate specified Dockerfile: Dockerfile

### ISSUE THREAD

**Issue by ACH1980** [zulip/docker-zulip#297]
Hi, I've this `docker-compose.yml`, but it gives me the "ERROR: Cannot locate specified Dockerfile: Dockerfile`:
```

version: '2'
services:
  database:
    image: 'zulip/zulip-postgresql:10'
    environment:
      POSTGRES_DB: 'zulip'
      POSTGRES_USER: 'zulip'
      POSTGRES_PASSWORD: '[Secure-password]'
    volumes:
      - '/opt/docker/zulip/postgresql/data:/var/lib/postgresql/data:rw'
  memcached:
    image: 'memcached:alpine'
    command:
      - 'sh'
      - '-euc'
      - |
        echo 'mech_list: plain' > "$$SASL_CONF_PATH"
        echo "zulip@$$HOSTNAME:$$MEMCACHED_PASSWORD" > "$$MEMCACHED_SASL_PWDB"
        echo "zulip@localhost:$$MEMCACHED_PASSWORD" >> "$$MEMCACHED_SASL_PWDB"
        exec memcached -S
    environment:
      SASL_CONF_PATH: '/home/memcache/memcached.conf'
      MEMCACHED_SASL_PWDB: '/home/memcache/memcached-sasl-db'
      MEMCACHED_PASSWORD: '[Secure-password]'
    restart: always
  rabbitmq:
    image: 'rabbitmq:3.7.7'
    hostname: zulip-rabbit
    restart: always
    environment:
        RABBITMQ_DEFAULT_USER: 'zulip'
        RABBITMQ_DEFAULT_PASS: '[Secure-password]'
    volumes:
      - '/opt/docker/zulip/rabbitmq:/var/lib/rabbitmq:rw'
  redis:
    image: 'redis:alpine'
    command:
      - 'sh'
      - '-euc'
      - |
        echo "requirepass '$$REDIS_PASSWORD'" > /etc/redis.conf
        exec redis-server /etc/redis.conf
    environment:
      REDIS_PASSWORD: '[Secure-password]'
    volumes:
      - '/opt/docker/zulip/redis:/data:rw'
  zulip:
    image: 'zulip/docker-zulip:3.4-0'
    build:
      context: .
      args:
        # Change these if you want to build zulip from a different repo/branch
        ZULIP_GIT_URL: https://github.com/zulip/zulip.git
        ZULIP_GIT_REF: '3.4'
        # Set this up if you plan to use your own CA certificate bundle for building
        # CUSTOM_CA_CERTIFICATES:
    ports:
      - '80:54080'
      - '443:51443'
    environment:
      DB_HOST: 'database'
      DB_HOST_PORT: '5432'
      DB_USER: 'zulip'
      SSL_CERTIFICATE_GENERATION: 'self-signed'
      SETTING_MEMCACHED_LOCATION: 'memcached:11211'
      SETTING_RABBITMQ_HOST: 'rabbitmq'
      SETTING_REDIS_HOST: 'redis'
      SECRETS_email_password: ',lf7HTa+GJe6l\kjgA^'
      # These should match RABBITMQ_DEFAULT_PASS, POSTGRES_PASSWORD,
      # MEMCACHED_PASSWORD, and REDIS_PASSWORD above.
      SECRETS_rabbitmq_password: '[Secure-password]'
      SECRETS_postgres_password: '[Secure-password]'
      SECRETS_memcached_password: '[Secure-password]'
      SECRETS_redis_password: '[Secure-password]'
      SECRETS_secret_key: '[Secure-secret]
      SETTING_EXTERNAL_HOST: 'localhost.localdomain'
      SETTING_ZULIP_ADMINISTRATOR: 'admin@example.com'
      SETTING_EMAIL_HOST: 'mail.hosting.de'  # e.g. smtp.example.com
      SETTING_EMAIL_HOST_USER: 'support@kanjias.de'
      SETTING_EMAIL_PORT: '587'
      # It seems that the email server needs to use ssl or tls and can't be used without it
      SETTING_EMAIL_USE_SSL: 'False'
      SETTING_EMAIL_USE_TLS: 'True'
      ZULIP_AUTH_BACKENDS: 'EmailAuthBackend'
      # Uncomment this when configuring the mobile push notifications service
      # SETTING_PUSH_NOTIFICATION_BOUNCER_URL: 'https://push.zulipchat.com'
    volumes:
      - '/opt/docker/zulip/zulip:/data:rw'
    ulimits:
      nofile:
        soft: 1000000
        hard: 1048576
```

A little research has shown, that it could be a problem with the `context`, but not absolute, maybe also another thing. I used the `docker-compose.yml`-File from this repository and only replaced the passwords and the external ports. If it could be a problem with the secure passwords, I could also paste the exact `docker-compose.yml` with those secure passwords, as I use random generated ones and it would be pretty easy to use another one in the next try...
