### ISSUE TITLE
Zulip server not able to connect to database

### ISSUE THREAD

**Issue by saad946** [zulip/docker-zulip#494]
**Title:** Zulip Pod Stuck in CrashLoopBackOff - "Waiting for database server to allow connections..."
`Executing Zulip configuration ...

**Description:** We are deploying Zulip in a Kubernetes cluster. All the dependencies (PostgreSQL, Redis, RabbitMQ, Memcached) are running and healthy, but the Zulip container is stuck in a crash loop. From the logs, it seems to be waiting for a database connection indefinitely, and then restarts.

**Problem:** Zulip fails at the bootstrap phase with the following log message:

`=== Begin Bootstrap Phase ===
Waiting for database server to allow connections ...
`

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zulip
  namespace: zulip
spec:
  serviceName: "zulip"
  replicas: 1
  selector:
    matchLabels:
      app: zulip
  template:
    metadata:
      labels:
        app: zulip
    spec:
      containers:
      - name: zulip
        image: zulip/docker-zulip:10.1-0
        ports:
        - containerPort: 80
        - containerPort: 443
        envFrom:
        - configMapRef:
            name: zulip-env
        volumeMounts:
        - name: zulip-storage
          mountPath: /data
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: "500m"
            memory: 1Gi
  volumeClaimTemplates:
  - metadata:
      name: zulip-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 20Gi
      storageClassName: standard



apiVersion: v1
kind: ConfigMap
metadata:
  name: zulip-env
  namespace: zulip
data:
  DB_HOST: "database"
  DB_HOST_PORT: "5432"
  DB_USER: "zulip"
  POSTGRES_DB: "zulip"
  POSTGRES_USER: "zulip"
  POSTGRES_PASSWORD: "BbAhcpK3tByeYUV"
  RABBITMQ_DEFAULT_USER: "zulip"
  RABBITMQ_DEFAULT_PASS: "wMYHr9n0xmVMkHq"
  MEMCACHED_PASSWORD: "uADWGsdvKew7S5I"
  REDIS_PASSWORD: "97uQnHDjijCVVVB"

  SSL_CERTIFICATE_GENERATION: "self-signed"
  SETTING_MEMCACHED_LOCATION: "memcached.zulip.svc.cluster.local:11211"
  SETTING_RABBITMQ_HOST: "rabbitmq.zulip.svc.cluster.local"
  SETTING_REDIS_HOST: "redis.zulip.svc.cluster.local"
  SETTING_REMOTE_POSTGRES_HOST: "postgres.zulip.svc.cluster.local"

  SECRETS_rabbitmq_password: "wMYHr9n0xmVMkHq"
  SECRETS_postgres_password: "BbAhcpK3tByeYUV"
  SECRETS_memcached_password: "uADWGsdvKew7S5I"
  SECRETS_redis_password: "97uQnHDjijCVVVB"
  SECRETS_secret_key: "<redacted>"



kubectl get svc -n zulip

NAME        TYPE           CLUSTER-IP       EXTERNAL-IP     PORT(S)        AGE
memcached   ClusterIP      34.118.227.118   <none>          11211/TCP      12m
postgres    ClusterIP      34.118.232.92    <none>          5432/TCP       12m
rabbitmq    ClusterIP      34.118.239.178   <none>          5672/TCP       12m
redis       ClusterIP      34.118.235.145   <none>          6379/TCP       12m
zulip       LoadBalancer   34.118.237.206   34.42.150.178   80:30887/TCP   8m




kubectl get pods -n zulip

NAME                         READY   STATUS             RESTARTS      AGE
memcached-6895d6bb4c-kj4t2   1/1     Running            0             12m
postgres-0                   1/1     Running            0             12m
rabbitmq-0                   1/1     Running            0             12m
redis-546b47bf66-scpqw       1/1     Running            0             12m
zulip-0                      0/1     CrashLoopBackOff   4 (25s ago)   8m
```

All databases are using same config map for simplicity, 

Highly appreciate if someone can help us out in this.
